### ISSUE TITLE
Why did you disable the tab control?

### ISSUE THREAD

**Issue by drudru** [MikeDunlavey/AucUI#1]
I see that you just made an hbox of buttons instead. Can you recall why you had to do that?

Also, what are the _COV statements?

**Comment by MikeDunlavey** [comment]
I had trouble making the tab control work, so I chickened out and used
buttons instead :)

The _COV macros are for coverage testing, if I remember right, it goes
something like this:
_COV expands to nothing.
But TCOV expands to some code that has a static local boolean, initially false.
When the code in the TCOV is executed, if the boolean is false, a
routine is called that records the text in the TCOV, and then sets the
boolean to true, so it's a 1-shot.
Then when the app shuts down, all those text labels that were executed
are written to a file, in a syntax that looks just like the TCOV
statements.
Outside, I can grep for TCOV in all the source files. Then I can
subtract the written file from the grepped file, and that leaves me
with a file of all the TCOV statements that were _not_ executed.
I can go through the source files, and for every TCOV that was
executed, I change it to _COV, so it won't be recorded again.
So that way, I can devise test scripts that will exercise every
pathway in the code.

If I want to do it all over again, I just do ^H and change all the _COV to TCOV.

I know there are tools for that, but I guess I'm just a do-it-yourselfer :)

**Comment by drudru** [comment]
Thanks for the reply! Makes sense :+1:
